module.exports = {
  // Only contains data from those published on npm
  familyData: {
    cache: {
      short_desc: '',
      long_desc: '',
      members: [
        '@seneca/cache',
        '@seneca/cache-test',
        '@seneca/entity-cache',
        '@seneca/memcached-cache',
        '@seneca/redis-cache',
      ],
      plugins: {},
    },
    entity: {
      short_desc: '',
      long_desc: '',
      members: [
        'seneca-entity',
        '@seneca/entity-cache',
        '@seneca/entity-depend',
        '@seneca/entity-history',
        '@seneca/entity-rtag',
        '@seneca/entity-util',
      ],
      plugins: {},
    },
    gateway: {
      short_desc: '',
      long_desc: '',
      members: [
        '@seneca/gateway',
        '@seneca/gateway-auth',
        '@seneca/gateway-express-auth',
        '@seneca/gateway-express',
        '@seneca/gateway-lambda',
      ],
      plugins: {},
    },
    msg: {
      short_desc: '',
      long_desc: '',
      members: ['@seneca/msg-run', 'seneca-msg-test'],
      plugins: {},
    },
    redis: {
      short_desc: '',
      long_desc: '',
      members: [
        '@seneca/redis-cache',
        'seneca-redis-pubsub-transport',
        'seneca-redis-queue-transport',
        'seneca-redis-store',
        'seneca-redis-kv',
      ],
      plugins: {},
    },
    search: {
      short_desc: '',
      long_desc: '',
      members: [
        'seneca-search-aws-cloudsearch',
        'seneca-search-elastic',
        '@seneca/search-mini',
        'seneca-search-test',
      ],
      plugins: {},
    },
    telemetry: {
      short_desc: '',
      long_desc: '',
      members: [
        'seneca-telemetry',
        '@seneca/telemetry-datadog',
        '@seneca/telemetry-newrelic',
        '@seneca/user-telemetry',
      ],
      plugins: {},
    },
    transport: {
      short_desc: '',
      long_desc: '',
      members: [
        'seneca-transport',
        'seneca-transport-test',
        'seneca-amqp-transport',
        'seneca-beanstalk-transport',
        '@seneca/sns-transport',
      ],
      plugins: {},
    },
    user: {
      short_desc: '',
      long_desc: '',
      members: ['@seneca/user', '@seneca/user-telemetry'],
      plugins: {},
    },
    web: {
      short_desc: '',
      long_desc: '',
      members: [
        'seneca-web',
        'seneca-web-adapter-connect',
        'seneca-web-adapter-express',
        'seneca-web-adapter-hapi',
        'seneca-web-adapter-koa1',
        'seneca-web-adapter-koa2',
      ],
      plugins: {},
    },
    logger: {
      short_desc: '',
      long_desc: '',
      members: [
        'seneca-logentries-logger',
        'seneca-logstash-logger',
        'seneca-pino-logger',
      ],
      plugins: {},
    },
    provider: {
      short_desc: '',
      long_desc: '',
      members: [
        'seneca-apimatic-provider',
        '@seneca/branchio-provider',
        'seneca-checklyhq-provider',
        '@seneca/eventbrite-provider',
        '@seneca/evervault-provider',
        'seneca-gcal-provider',
        '@seneca/github-provider',
        'seneca-gitlab-provider',
        'seneca-hubspot-provider',
        'seneca-meetup-provider',
        '@seneca/mixpanel-provider',
        '@seneca/nordigen-provider',
        'seneca-notion-provider',
        'seneca-orbit-provider',
        'seneca-salesforce-provider',
        'seneca-stytch-provider',
        '@seneca/tangocard-provider',
        '@seneca/trello-provider',
        '@seneca/vercel-provider',
        'seneca-webflow-provider',
        'seneca-zoom-provider',
        'seneca-customerio-provider',
      ],
      plugins: {},
    },
    store: {
      short_desc: '',
      long_desc: '',
      members: [
        '@seneca-dynamo-store',
        'seneca-jsonfile-store',
        '@seneca-knex-store',
        'seneca-level-store',
        'seneca-mem-store',
        'seneca-mongo-store',
        'seneca-mysql-store',
        'seneca-postgres-store',
        'seneca-redis-store',
        '@seneca-s3-store',
        'seneca-sqlite-store',
      ],
      plugins: {},
    },
    test: {
      short_desc: '',
      long_desc: '',
      members: [
        '@seneca/cache-test',
        'seneca-error-test',
        'search-test',
        'seneca-store-test',
        'seneca-transport-test',
        'seneca-msg-test',
        '@seneca/test-plugin',
      ],
      plugins: {},
    },
    registry: {
      short_desc: '',
      long_desc: '',
      members: ['seneca-registry', 'seneca-consul-registry'],
      plugins: {},
    },
    various: {
      short_desc: '',
      long_desc: '',
      members: [
        '@seneca/flame',
        '@seneca/debug',
        'seneca-basic',
        '@seneca/ledger',
        '@seneca/maintain',
        '@seneca/request',
        '@seneca/mail',
        'seneca-balance-client',
        '@seneca/graph',
        '@seneca/gateway',
        '@seneca/repl',
        '@seneca/refer',
        'seneca-browser',
        '@seneca/flow',
        '@seneca/vote',
        '@seneca/env',
        '@seneca/allow',
        '@seneca/apikey',
        'seneca-joi',
        'seneca-mesh',
        'seneca-kv',
        'seneca-log-filter',
        'seneca-auth',
        'seneca-parambulator',
        '@seneca/config',
        '@seneca/doc',
        'seneca-group',
        '@seneca/hapi',
        '@seneca/external',
        'seneca-populate',
        'seneca-monitor',
        '@seneca/owner',
        'seneca-promisify',
        'seneca-member',
        'seneca-sendgrid-mail',
        '@seneca/srv-admin',
        'seneca-component',
      ],
      plugins: {},
    },
  },
}
